### **import numpy library**

In [1]:
import numpy as np

### **the basics**

In [2]:
a = np.array([1,2,3]) # 1D array
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]]) # nest list within a list
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# getting dimension of the numpy array
a.ndim

2

In [ ]:
# getting dimension of the numpy array
b.ndim

2

In [ ]:
# get shape
a.shape
# a is 1D -> 3 rows, 1 column
# mistake here - in 1D array it doesn't actually have rows and columns at all, so output (3,) just means 3 elements in 1D 

(3,)

In [13]:
b.shape
# 2 rows, 3 columns

(2, 3)

In [ ]:
# get type
# type of data stored
a.dtype 
# if wanted to specify what type we wanted it to store as -> a = np.array([1,2,3], dtype = 'int16')

dtype('int64')

In [ ]:
# get size
# tells how many bytes each element makes up (64 bits = 8 bytes)
a.itemsize

8

In [ ]:
# get total size
# total number of elemnts
a.size

3

In [17]:
# total memory array takes up in bytes
a.size * a.itemsize

24

In [19]:
# another way to do that
a.nbytes

24

### **accessing/changing specific elements, rows, columns, etc**

In [20]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]) # 2 X 7 array
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c]
# 0 BASED INDEXING KEEP IN MIND
# # can also use negative notation like lists -> a[1, -2] will also give the same output
a[1, 5]
# here o/p = np.int64(13)
# if want o/p just 13 wrap it in int -> int(a[1, 5]) -> gives 13

np.int64(13)

In [22]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]
# want the first row, start at the 1st element, end at 6th element(6th elements exclusive)/-1th element(-1th element exclusive), step size 2

array([2, 4, 6])

In [25]:
# changing an element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [27]:
# changin an entire column
a[:,2] = 5
print(a)
a[:,2] = [1,2] 
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3D example

In [28]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
# Get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [30]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [33]:
# replacing
# have to create a subsequence that's the same dimension
b[:,1,:] = [[9,9], [8,8]]
print(b)
# as long as it is the same dimension, it will work, otherwise it will throw a value error

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### **intialising different types of arrays**

In [34]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix
np.ones((4,2,2), dtype='int32') # can also specify data type here 

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# Any other number
np.full((2,2), 99, dtype = 'float32') # can also specify data type

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [38]:
# Any other number (full_like)
np.full_like(a, 4)
# allows us to take a shape that's already built
# eg here we took the same size as array a

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [39]:
# if not used full_like we would have to pass a.shape
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [42]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.67017922, 0.99405127],
       [0.92709244, 0.11992015],
       [0.70120843, 0.81799616],
       [0.37870904, 0.80202233]])

In [43]:
# want to pass a shape
np.random.random_sample(a.shape)

array([[0.28963861, 0.16228442, 0.75780869, 0.7621461 , 0.99930867,
        0.47549079, 0.40936119],
       [0.58449489, 0.26984373, 0.83414861, 0.35935353, 0.58781864,
        0.16945573, 0.71493076]])

In [ ]:
# Random Integer values
np.random.randint(7, size = (3,3))
# the 7 says we want our range of ints in the matrix to be from 0 to 7(exclusive) -> 7 was the end which we specified, if we did not specify start, it assumes 0
# can also do np.random.randint(4, 7, size = (3,3)) -> now will have integers 4 to 7 in the matrix
# can also do -ve numbers

array([[3, 5, 5],
       [5, 2, 2],
       [0, 3, 4]], dtype=int32)

In [ ]:
# The identity matrix
np.identity(5)
# only takes 1 parameter as it is by default a square matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [47]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


#### excercise
make this array without manually typing in each and every number
|1|1|1|1|1|
|---|---|---|---|---|
|1|0|0|0|1|
|1|0|9|0|1|
|1|0|0|0|1|
|1|1|1|1|1|

In [55]:
output = np.ones((5,5))
print(output)

# filling middle elements of output with zeros
z = np.zeros((3,3)) 
# filling middle element with 9
z[1,1] = 9
print(z)

# replacing middle part of ones matrix
output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [60]:
a = np.array([1,2,3])

b = a
print(b)
b[0] = 100
print(b)
print(a) # we changed in b but it even changed in a because variable named b points to the same thing as a does

a = np.array([1,2,3])
b = a.copy()
print(b)
b[0] = 100
print(b)
print(a) # changing in b doesn't change in a as we are copying contents of a into b

[1 2 3]
[100   2   3]
[100   2   3]
[1 2 3]
[100   2   3]
[1 2 3]


### **mathematics**

In [62]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 2 # elementwise addition

array([3, 4, 5, 6])

In [65]:
a - 2 # elementwise subtraction

array([-1,  0,  1,  2])

In [66]:
a * 2

array([2, 4, 6, 8])

In [67]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [68]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [ ]:
a ** 2 # power

array([ 1,  4,  9, 16])

In [70]:
# Take the sin or cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [71]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### **linear algebra**

In [ ]:
# matrix multiplication
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [73]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

numpy can do 
- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse
- Etc...

### **statistics**

In [74]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [75]:
np.min(stats)

np.int64(1)

In [76]:
np.max(stats)

np.int64(6)

In [77]:
# min of the 1st row and min of the 2nd row
np.min(stats, axis=1)

array([1, 4])

In [78]:
np.min(stats, axis=0)
# gives all the values at the top as those are all the mins

array([1, 2, 3])

In [79]:
np.max(stats, axis=1)

array([3, 6])

In [80]:
# sum of all elements of the matrix
np.sum(stats)

np.int64(21)

In [82]:
# adds up all the terms going downwards
np.sum(stats, axis=0)

array([5, 7, 9])

### **reorganizing arrays**

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape) # (2, 4)
# we wanna make it a 8x1
after = before.reshape((8,1))
print(after)
after = before.reshape((4,2))
print(after)
after = before.reshape((2,2,2)) # we can do any combination as long as it has the same amount of values
print(after)
# what doesn't work
# after = before.reshape((2,3)) # this will give error as there is a difference between the shape we're trying to resize it to and the original shape
# print(after)


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [91]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
# can only do this if sizes match, if they mismatch, it will throw error

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [90]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### **miscellaneous**

load data from file

In [98]:
# get data from file as an array
filedata = np.genfromtxt('data.txt', delimiter = ',')
print(filedata)
# it is automatically casted to a float type
# if we want an integer
filedata.astype('int32') # this actually makes a copy as float type and int32 type are different sizes and it can't in place copy everything
print(filedata) # here back to float value
filedata = filedata.astype('int32')
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


boolean masking and advanced indexing

In [100]:
# where in filedata we have greater than 50
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [101]:
# can index based on where it is greater than 50
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [103]:
# we can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]] # gives 2,3,9 -> we passed a list and it indexed those

array([2, 3, 9])

In [ ]:
np.any(filedata > 50, axis = 0)
# if we looked downwards are ANY of the values greater than 50, even if any one greater than 50 -> true

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [105]:
np.all(filedata > 50, axis = 0)
# only if ALL values are greater than 50 -> true

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [106]:
np.all(filedata > 50, axis = 1)
# gonna be the rows

array([False, False, False])

In [109]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [110]:
# not
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

#### excercise

|1|2|3|4|5|
|---|---|---|---|---|
|6|7|8|9|10|
|11|12|13|14|15|
|16|17|18|19|20|
|21|22|23|24|25|
|26|27|28|29|30|

Q1) index this part of the matrix 
|11|12|
|---|---|
|16|17|

it is the 2nd and 3rd row and the 0th and 1st column -> a[2:4, 0:2]

Q2) how to index this part -> 2 -> 8 -> 14 -> 20 (diagonal)
need to use 2 different lists within our indexing, a[[0,1,2,3] , [1,2,3,4]] (0,1,2,3 row with 1,2,3,4 columns)

Q3) how to index -> 4,5
                    24,25
                    29,30
a[[0,4,5], 3:] -> 0,4,5 rows and columns 3 onwards