import numpy library

In [1]:
import numpy as np

the basics

In [2]:
a = np.array([1,2,3]) # 1D array
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]]) # nest list within a list
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# getting dimension of the numpy array
a.ndim

2

In [ ]:
# getting dimension of the numpy array
b.ndim

2

In [ ]:
# get shape
a.shape
# a is 1D -> 3 rows, 1 column
# mistake here - in 1D array it doesn't actually have rows and columns at all, so output (3,) just means 3 elements in 1D 

(3,)

In [13]:
b.shape
# 2 rows, 3 columns

(2, 3)

In [ ]:
# get type
# type of data stored
a.dtype 
# if wanted to specify what type we wanted it to store as -> a = np.array([1,2,3], dtype = 'int16')

dtype('int64')

In [ ]:
# get size
# tells how many bytes each element makes up (64 bits = 8 bytes)
a.itemsize

8

In [ ]:
# get total size
# total number of elemnts
a.size

3

In [17]:
# total memory array takes up in bytes
a.size * a.itemsize

24

In [18]:
# another way to do that
a.nbytes

24