import numpy library

In [1]:
import numpy as np

the basics

In [2]:
a = np.array([1,2,3]) # 1D array
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]]) # nest list within a list
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# getting dimension of the numpy array
a.ndim

2

In [ ]:
# getting dimension of the numpy array
b.ndim

2

In [ ]:
# get shape
a.shape
# a is 1D -> 3 rows, 1 column
# mistake here - in 1D array it doesn't actually have rows and columns at all, so output (3,) just means 3 elements in 1D 

(3,)

In [13]:
b.shape
# 2 rows, 3 columns

(2, 3)

In [ ]:
# get type
# type of data stored
a.dtype 
# if wanted to specify what type we wanted it to store as -> a = np.array([1,2,3], dtype = 'int16')

dtype('int64')

In [ ]:
# get size
# tells how many bytes each element makes up (64 bits = 8 bytes)
a.itemsize

8

In [ ]:
# get total size
# total number of elemnts
a.size

3

In [17]:
# total memory array takes up in bytes
a.size * a.itemsize

24

In [19]:
# another way to do that
a.nbytes

24

accessing/changing specific elements, rows, columns, etc

In [20]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]) # 2 X 7 array
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c]
# 0 BASED INDEXING KEEP IN MIND
# # can also use negative notation like lists -> a[1, -2] will also give the same output
a[1, 5]
# here o/p = np.int64(13)
# if want o/p just 13 wrap it in int -> int(a[1, 5]) -> gives 13

np.int64(13)

In [22]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]
# want the first row, start at the 1st element, end at 6th element(6th elements exclusive)/-1th element(-1th element exclusive), step size 2

array([2, 4, 6])

In [25]:
# changing an element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [27]:
# changin an entire column
a[:,2] = 5
print(a)
a[:,2] = [1,2] 
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3D example

In [28]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
# Get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [30]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
# replacing
# have to create a subsequence that's the same dimension
b[:,1,:] = [[9,9], [8,8]]
print(b)
# as long as it is the same dimension, it will work, otherwise it will throw a value error

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
